import { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      map: 'Carte',
      knowledge: 'Base de connaissances',
      suppliers: 'Fournisseurs',
      dashboard: 'Tableau de bord',
      register: 'S\'inscrire',
      admin: 'Admin',
      lang: 'EN',
    },
    home: {
      hero: 'La plateforme gratuite pour les aquaculteurs africains',
      heroSub: 'Enregistrez votre exploitation, suivez votre production, accédez aux connaissances FAO et connectez-vous aux fournisseurs.',
      cta: 'Enregistrez votre exploitation',
      ctaSub: 'Gratuit — Rejoignez 500+ opérateurs',
      feature1: 'Suivi de production',
      feature1desc: 'Enregistrez vos récoltes, ensemencements et incidents. Calculez votre FCR et suivez vos performances.',
      feature2: 'Base FAO',
      feature2desc: 'Fiches techniques sur les espèces, maladies, alimentation et qualité de l\'eau selon les standards FAO.',
      feature3: 'Fournisseurs',
      feature3desc: 'Trouvez des fournisseurs d\'équipements, d\'aliments et d\'alevins certifiés en Afrique et à l\'international.',
      how: 'Comment ça marche',
      step1: 'Inscrivez-vous',
      step1desc: 'Enregistrez votre exploitation en 3 étapes simples',
      step2: 'Suivez',
      step2desc: 'Enregistrez vos productions et accédez à votre tableau de bord',
      step3: 'Progressez',
      step3desc: 'Bénéficiez de recommandations et connectez-vous aux experts',
      stats: 'opérateurs enregistrés',
      countries: 'pays',
      fcr: 'FCR moyen',
    },
    footer: 'AquaMap Africa — Développé avec ❤️ pour les aquaculteurs africains',
    register: {
      title: 'Enregistrer votre exploitation',
      step1: 'Identité',
      step2: 'Exploitation',
      step3: 'Production',
      name: 'Nom complet',
      phone: 'Téléphone',
      country: 'Pays',
      region: 'Région',
      gps: 'Localisation GPS',
      gpsBtn: '📍 Capturer position',
      gender: 'Genre',
      ageRange: 'Tranche d\'âge',
      legalStatus: 'Statut juridique',
      units: 'Nombre d\'unités',
      area: 'Surface totale (m²)',
      system: 'Système de culture',
      species: 'Espèces élevées',
      waterSource: 'Source d\'eau',
      electricity: 'Accès à l\'électricité',
      road: 'Accès routier',
      production: 'Production annuelle estimée (tonnes)',
      revenue: 'Revenus annuels estimés (FCFA)',
      sales: 'Canal de vente principal',
      financing: 'Avez-vous un financement ?',
      challenges: 'Principaux défis (max 3)',
      training: 'Souhaitez-vous une formation ?',
      next: 'Suivant →',
      prev: '← Précédent',
      submit: 'Enregistrer mon exploitation',
      success: 'Votre exploitation a été enregistrée ✓',
      successSub: 'Bienvenue dans AquaMap Africa ! Accédez à votre tableau de bord.',
      dashboard: 'Accéder au tableau de bord',
      yes: 'Oui',
      no: 'Non',
      male: 'Homme',
      female: 'Femme',
      other: 'Autre',
    },
    dashboard: {
      welcome: 'Bienvenue,',
      fcr: 'FCR actuel',
      production: 'Production ce trimestre',
      revenue: 'Revenus estimés',
      harvest: 'Prochaine récolte',
      addHarvest: '+ Enregistrer une récolte',
      addSeed: '+ Enregistrer un ensemencement',
      incident: 'Signaler un incident',
      trend: 'Tendance de production (6 mois)',
      fcrGauge: 'Indice de Conversion Alimentaire',
      fcrCalc: 'Calculateur FCR',
      feed: 'Aliments distribués (kg)',
      weight: 'Gain de poids (kg)',
      calculate: 'Calculer',
      logHarvest: 'Enregistrer une récolte',
      date: 'Date',
      speciesLabel: 'Espèce',
      kgHarvested: 'Kg récoltés',
      kgSold: 'Kg vendus',
      pricePerKg: 'Prix/kg (FCFA)',
      buyerType: 'Type d\'acheteur',
      save: 'Enregistrer',
      cancel: 'Annuler',
    },
    map: {
      title: 'Carte des opérateurs',
      filters: 'Filtres',
      country: 'Pays',
      species: 'Espèce',
      system: 'Système',
      scale: 'Échelle',
      all: 'Tous',
      stats: 'Statistiques par pays',
      operators: 'opérateurs',
    },
    knowledge: {
      title: 'Base de connaissances',
      subtitle: 'Fiches techniques FAO pour l\'aquaculture africaine',
      featured: 'Article à la une',
      read: 'Lire la fiche →',
      categories: {
        all: 'Tout',
        species: 'Espèces',
        disease: 'Maladies',
        feed: 'Alimentation',
        water: 'Qualité de l\'eau',
        ras: 'RAS',
        regulation: 'Réglementation',
      },
    },
    suppliers: {
      title: 'Fournisseurs d\'équipements',
      subtitle: 'Trouvez les meilleurs fournisseurs pour votre exploitation',
      contact: 'Contacter',
      cta: 'Devenir fournisseur partenaire',
      ctaDesc: 'Rejoignez notre réseau et connectez-vous à 500+ opérateurs africains',
      ctaBtn: 'Soumettre votre candidature',
      categories: {
        all: 'Tous',
        ras: 'Systèmes RAS',
        feed: 'Aliments',
        fingerling: 'Alevins',
        aeration: 'Aération',
        water: 'Tests qualité eau',
      },
    },
    admin: {
      title: 'Tableau de bord Administrateur',
      password: 'Mot de passe',
      login: 'Connexion',
      wrongPass: 'Mot de passe incorrect',
      stats: 'Statistiques nationales',
      operators: 'Opérateurs',
      export: '📥 Exporter CSV',
      fcrDist: 'Distribution FCR',
      challenges: 'Principaux défis',
      filterCountry: 'Filtrer par pays',
      filterSpecies: 'Filtrer par espèce',
      filterScale: 'Filtrer par échelle',
      all: 'Tous',
    },
  },
  en: {
    nav: {
      home: 'Home',
      map: 'Map',
      knowledge: 'Knowledge Base',
      suppliers: 'Suppliers',
      dashboard: 'Dashboard',
      register: 'Register',
      admin: 'Admin',
      lang: 'FR',
    },
    home: {
      hero: 'The free platform for African aquaculture farmers',
      heroSub: 'Register your farm, track your production, access FAO knowledge and connect with suppliers.',
      cta: 'Register your farm',
      ctaSub: 'Free — Join 500+ operators',
      feature1: 'Production tracking',
      feature1desc: 'Record harvests, stocking and incidents. Calculate your FCR and monitor performance.',
      feature2: 'FAO Knowledge Base',
      feature2desc: 'Technical sheets on species, diseases, feed and water quality per FAO standards.',
      feature3: 'Equipment Suppliers',
      feature3desc: 'Find certified equipment, feed and fingerling suppliers across Africa and internationally.',
      how: 'How it works',
      step1: 'Register',
      step1desc: 'Register your farm in 3 simple steps',
      step2: 'Track',
      step2desc: 'Log your production and access your dashboard',
      step3: 'Grow',
      step3desc: 'Get recommendations and connect with experts',
      stats: 'registered operators',
      countries: 'countries',
      fcr: 'Average FCR',
    },
    footer: 'AquaMap Africa — Built with ❤️ for African aquaculture farmers',
    register: {
      title: 'Register your farm',
      step1: 'Identity',
      step2: 'Farm Profile',
      step3: 'Production',
      name: 'Full name',
      phone: 'Phone',
      country: 'Country',
      region: 'Region',
      gps: 'GPS location',
      gpsBtn: '📍 Capture position',
      gender: 'Gender',
      ageRange: 'Age range',
      legalStatus: 'Legal status',
      units: 'Number of units',
      area: 'Total area (m²)',
      system: 'Culture system',
      species: 'Species',
      waterSource: 'Water source',
      electricity: 'Electricity access',
      road: 'Road access',
      production: 'Estimated annual production (tonnes)',
      revenue: 'Estimated annual revenue (FCFA)',
      sales: 'Main sales channel',
      financing: 'Do you have financing?',
      challenges: 'Main challenges (max 3)',
      training: 'Do you want training?',
      next: 'Next →',
      prev: '← Back',
      submit: 'Register my farm',
      success: 'Your farm has been registered ✓',
      successSub: 'Welcome to AquaMap Africa! Access your dashboard.',
      dashboard: 'Go to dashboard',
      yes: 'Yes',
      no: 'No',
      male: 'Male',
      female: 'Female',
      other: 'Other',
    },
    dashboard: {
      welcome: 'Welcome,',
      fcr: 'Current FCR',
      production: 'Production this quarter',
      revenue: 'Estimated revenue',
      harvest: 'Next harvest',
      addHarvest: '+ Log harvest',
      addSeed: '+ Log stocking',
      incident: 'Report incident',
      trend: 'Production trend (6 months)',
      fcrGauge: 'Feed Conversion Ratio',
      fcrCalc: 'FCR Calculator',
      feed: 'Feed distributed (kg)',
      weight: 'Weight gain (kg)',
      calculate: 'Calculate',
      logHarvest: 'Log harvest',
      date: 'Date',
      speciesLabel: 'Species',
      kgHarvested: 'Kg harvested',
      kgSold: 'Kg sold',
      pricePerKg: 'Price/kg (FCFA)',
      buyerType: 'Buyer type',
      save: 'Save',
      cancel: 'Cancel',
    },
    map: {
      title: 'Operator Map',
      filters: 'Filters',
      country: 'Country',
      species: 'Species',
      system: 'System',
      scale: 'Scale',
      all: 'All',
      stats: 'Statistics by country',
      operators: 'operators',
    },
    knowledge: {
      title: 'Knowledge Base',
      subtitle: 'FAO technical sheets for African aquaculture',
      featured: 'Featured article',
      read: 'Read sheet →',
      categories: {
        all: 'All',
        species: 'Species',
        disease: 'Diseases',
        feed: 'Feed',
        water: 'Water quality',
        ras: 'RAS',
        regulation: 'Regulation',
      },
    },
    suppliers: {
      title: 'Equipment Suppliers',
      subtitle: 'Find the best suppliers for your farm',
      contact: 'Contact',
      cta: 'Become a partner supplier',
      ctaDesc: 'Join our network and connect with 500+ African operators',
      ctaBtn: 'Submit application',
      categories: {
        all: 'All',
        ras: 'RAS Systems',
        feed: 'Feed',
        fingerling: 'Fingerlings',
        aeration: 'Aeration',
        water: 'Water quality tests',
      },
    },
    admin: {
      title: 'Admin Dashboard',
      password: 'Password',
      login: 'Login',
      wrongPass: 'Incorrect password',
      stats: 'National statistics',
      operators: 'Operators',
      export: '📥 Export CSV',
      fcrDist: 'FCR Distribution',
      challenges: 'Main challenges',
      filterCountry: 'Filter by country',
      filterSpecies: 'Filter by species',
      filterScale: 'Filter by scale',
      all: 'All',
    },
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = translations[lang];
  const toggle = () => setLang(l => l === 'fr' ? 'en' : 'fr');
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
